### PR TITLE
build

### PR DESCRIPTION
**Pull request by forrestguice**
For your consideration.. Take it, leave it, or reproduce these changes on your own. I'm kind of ambivalent, but happened to notice this issue (#8) mentioned briefly on F-Droid [forum](https://forum.f-droid.org/t/cant-install-apps-via-f-droid/8337/20) and thought this might be helpful. 

Changes:
* added gradle build files; the existing project structure was preserved (so the existing ant build should continue to function.
* incremented the targetSdkVersion from `21` to `23`. I think this is sufficient to avoid the "ancient android" warning that was mentioned in #8.
* fixes a few problems identified by lint (its important to verify that `gradlew lintVitalRelease` completes without errors or the F-Droid build will probably fail later).

This is a first step toward a new release.
To get the new version on F-Droid you'll need to use the Github [releases](https://github.com/allan-simon/verbiste-android/releases) page to create tag, modify the F-Droid [metadata](https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/com.allansimon.verbisteandroid.yml) to point to that tag, then submit a pullrequest to fdroiddata. They'll probably suggest adding [fastlane](https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/) to the project.

Here's what my [metadata](https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/com.forrestguice.suntimeswidget.yml) looks like as an example. Note the relative (lack of) complexity - I think a benefit to updating the build will be to simplify future project maintenance.

### CODE REVIEW

**Review by allan-simon — APPROVED** [review]

**Comment by allan-simon** [comment]
thanks a lot :) 

btw  as I'm more of a web developper than a android one (I think you can guess it by how ugly the app is) I've been wondering lately to make a new version of it in react-native (for which I have some experience on some other hobby project) and I was wondering how it was easy or not to get react-native app in f-droid ?

**Comment by allan-simon** [comment]
https://gitlab.com/fdroid/fdroiddata/merge_requests/6246/diffs I've made the pull request

**Comment by forrestguice** [comment]
Sorry. I'm not really familiar with react-native. I don't know.

By the way I'm reviewing the `app/build.xml` file from yesterday and realized that I forgot a few things. You will need to add these lines to the `defaultConfig {}` block (next to targetSdkVersion) and retag it:

`versionCode 2`
`versionName "1.1"`

Sorry for neglecting this. These used to be defined in AndroidManifest.xml, but gradle actually replaces these definitions with its own. You'll need to increment these numbers before tagging each release.

**Comment by forrestguice** [comment]
Also, you will need to modify latest metadata entry to use gradle (instead of ant). I think it needs to look something like..

```
 - versionName: 1.1
    versionCode: 2
    commit: v1.1
    prebuild:
      - pushd utils
      - python xml2sqlite.py
      - popd
    subdir: app
    gradle:
      - yes
```
but I'm not entirely sure I've got that `prebuild` step right. The F-Droid maintainers will have some comments I'm sure..

**Comment by forrestguice** [comment]
Actually.. it looks like replacing the ant metadata entry with a gradle one is optional in this case. The preexisting ant build still works, so that definition you added probably works too. I would switch it over anyway (since the metadata needs to be edited either way it seems like a good opportunity).

**Pull request merged**
